class CfgExileLoadingScreen
{
	templates[]=
	{
		// FK
		{"They refused to give me tea so I rebelled", "CatCaptain"},
		{"Rule#1: There is always one more guy.", "StormC4G"},
		{"Pro Tip: Use the parachuting Bambi's as target practice", "TreeSugar"},
		{"Arma skill is measured by who can wait longer in pine trees", "OutdatedBoss"},
		{"Press G to open your pack!", "kurt.pdf"},
		{"Turn grass on", "KHZero"},
		{"When the sun goes down the gamma goes up", "Erron White"},
		{"No Vid? No Comp.", "Oscarlikestacos"},
		{"Dumping Virtual Garage...", "haxo"},
		{"Filling your safe with random garbage", "thak"},
		{"Removing wheels in 3....2.....1", "Gundam"},
		{"Don't trust that Maxi guy...", "Luke Lawnmower Peeters"},
		{"Typing in sidechat", "Magz"},
		{"Initiating alt f4 protocol...", "Black Knight"},
		{"everyone hold onto something, crafting incoming...", "Mario"},
		{"Putting the same code for every door in the base...", "Fried Rice"},
		{"Red container, exile space program", "CatCaptain"},
		{"Spawning character in middle of ocean", "Dr.Mailman"},
		{"CP in and out - 15 minute adventure", "StormC4G"},
		{"Eating your magazines", "Hawk"},
		{"Carole Fucking Baskin", "Magz"},
		{"Spawning rock 10ft ahead", "Gundam"},
		{"BattleEye Client Not Responding...", "Nick?"},
		{"Duct taping engine", "OutdatedBoss"},
		{"crafting in session........you have disconnected", "n00b_sQuaD"},
		{"Have you tried 0000 yet?", "Oscarlikestacos"},
		{"I'm never gonna financially recover from this.", "StormC4G"},
		{"Happy Mothers Day mama Niehlis!!!!", "Oscarlikestacos"},
		{"This is an RP server right?", "haxo"},
		{"FrankieonPCin1080p waiting room", "Oscarlikestacos"},
		{"I'm not camping, it's tactical waiting!", "Luke Lawnmower Peeters"},
		{"I once was a soldier like you, than I took a car to the knee", "Black Knight"},
		{"Caution, the AI use aimbots.", "Clerius"},
		{"Bushwookies, Bushwookies everywhere", "CatCaptain"},
		{"Raising your lowered terrain", "Magz"},
		{"Friendly in cherno?", "MacabreDelVal"},
		{"There's a player! Oh wait its  a bush...", "Bulson"},
		{"Certified play to win server!", "Erron White"},
		{"Yeah, I can fly the chopper...famous last words", "chad"},
		{"FUCKING LAG", "lefty0110"},
		{"Trust me. Super Stallions can land in the ocean.", "Nick?"},
		{"Under the sea, down where it's better down where it's wetter", "kurt.pdf"},
		{"hiding In my ambush bush", "intense intents in tents"},
		{"Lamps in video games are using real electricity", "Gundam"},
		{"Remember to get snacks before camping.", "CatCaptain"},
		{"What the fuck is that... yep probably Oscar", "lefty0110"},
		{"Broke Leg, no meds...respawn", "Gundam"},
		{"Damn bikes", "Luke Lawnmower Peeters"},
		{"Remember son, bushes are made out of concrete", "CatCaptain"},
		{"It's not about the money, it's about the message", "Kindle"},
		{"Bambis Welcome", "Parmesan King"},
		{"Walmart Riot complete... choose your spawn location", "Conflict"},
		{"Quads... Quads everywhere!", "Magz"},
		{"Kamenka is a Bambi Grave", "Logan"},
		{"Soon(TM)", "WolfkillArcadia"},
		{"L'orange...Mmm, succulawhnt...", "teh_neb"},
		{"Put it in reverse, Terry!!", "teh_neb"},
		{"Wait a bit, I'm in the middle of some calibrations...", "acer5200"},
		{"First ATV in Space", "Gundam"},
		
		
		// EXILE
		{"Attaching vehicles to bungee cords.", "4mbu5h"},
		{"Attempting to utilize the GPU... Failed... Reverting to CPU...", "Tobias Solem"},
		{"Bad module error", "ComatoseBadger"},
		{"Booby trapping push bikes...", "HonestDave"},
		{"Booking Flight To Altis", "Bloodsworth"},
		{"Breaking helicopter for no reason.", "Gryph"},
		{"But where are all the zombies at?", "Midnight"},
		{"Can't answer the phone right now! I'm playing Arma!", "OG ThaGame"},
		{"Deploying Raiding Bandits...", "Zentarix"},
		{"Disperse these spongers", "Sgt. Cuddles"},
		{"Do you kno dawae?", "MonkeyNutz"},
		{"Don't ALT+TAB!", "Michaesine"},
		{"Dropping tables...", "Jefferderp"},
		{"Emergerrrd look...helerkerpters", "masters91"},
		{"Emptying your locker...", "[KZ] Samfisher"},
		{"Error: Bambi Creation Timeout", "AdamKadmon"},
		{"Error: This game is no longer available", "Cooper"},
		{"ExtDB3 support, when?", "Cloud"},
		{"Feeding horse for power...", "primedead"},
		{"Have you tried switching it off and on again?", "ExiledVibe"},
		{"Headless client midlife crisis: Wants head back", "Antdooky"},
		{"Hey, WolfkillArcadia. Let me have a loading screen quote!", "Defent"},
		{"Hiding IEDs on the road...", "Aramet"},
		{"I got knife, let's steal... *dies at car*", "Reaper7Strike"},
		{"I have no problems on other servers", "James1st"},
		{"I should've read a tutorial...", "BushWuukie"},
		{"In real life, Altis is called Lemnos", "science freak"},
		{"iPhone XM8 when?", "CatOverload"},
		{"Kuplion isn't really that awesome", "Devil_Wolf"},
		{"Loading Rage Quit Engine", "smokedog77"},
		{"Loading Spoilers", "Bloodsworth"},
		{"Log in successful, informing raiders...", "Feary"},
		{"Looking damn good, my man!", "ZeroSuitSnake"},
		{"Manufacturing wooden ammunition", "pticu"},
		{"Mission time? Mission time", "MilkyBob"},
		{"No Keyboard Detected! Press F1 To Continue", "Captain_Bigzy"},
		{"No.", "Vishpala"},
		{"Perf isn't really critical so this will do in the meantime.", "Killjoy"},
		{"Praying to the Loot God", "Twent"},
		{"Refining death mechanics...", "Nightshredder"},
		{"Rooty Tooty, Point and Shooty!", "Demonic"},
		{"Server restart in 1 minute!", "Jarskie"},
		{"Servers are dumb", "Andrew_S90"},
		{"TheMeq W0z Er3", "TheMeq"},
		{"This is a Life server, right?", "FairyTale"},
		{"This is chaos", "AwezmTV"},
		{"This is not what I signed up for ", "UnknownWarrior"},
		{"This message intentionally left blank.", "Geekm0nkey"},
		{"This server is powered by a lemon and two electrodes.", OMARCOMIN},
		{"Trying to find the one safe spot", "pipin96"},
		{"Verify Integrity of Game Files...", "Helldog"},
		{"Waaaaiiit, Woooot ?", REX},
		{"Why?", "StokesMagee"},
		{"Your XM8 shut down unexpectedly. Please restart your PC.", "Przemek"},
		{"Mornin! Nice day for fishin, ain't it? Hu hah!", "Eichi"},
		{"Throwing hand grenade at a rabbit...", "ass4assintim"},
		{"Milking the sheep", "Trap_God"},
		{"Status of happening: It is", "qp"},
		{"Just a fat little squirrel trying to get a nut", "chainsaw"},
		{"... Do not ping me with en random ... !!!", "Dwarden"},
		{"Loading Chicken...", "Dave"},
		{"Dropping GBU on your location", "Dark4Ever[MGK]"},
		{"Stealing your Семечки", "Bambuz"},
		{"Randomizing PIN codes...", "Coldrice"},
		{"Installing OP Frying Pan", "Morty"},
		{"You need a little revive?", "Falinov"},
		{"I love you mom and dad", "H0nkX"},
		{"Preparing to find THE way", "The Dude (chernaruski)"},
		{"Paying for WinRAR", "IPaidForWinRAR"}
	};
		
};