// Generated by unRap v1.06 by Kegetys

class CfgMusic {
	class ExileTrack01 {
		duration = 170;
		musicClass = "Lead";
		name = "Exile Track 01 - Main Theme";
		sound[] = {"", 1, 1};
	};
	
	class ExileTrack02 {
		duration = 223;
		musicClass = "Lead";
		name = "Exile Track 02 - Welcome to Exile (Menu Version)";
		sound[] = {"", 1, 1};
	};
	
	class ExileTrack03 {
		duration = 170;
		musicClass = "Lead";
		name = "Exile Track 03 - Welcome to Exile (Original Composition)";
		sound[] = {"", 1, 1};
	};
	
	class ExileTrack04 {
		duration = 317;
		musicClass = "Calm";
		name = "Exile Track 04 - The Island (Roaming Ambience)";
		sound[] = {"", 1, 1};
	};
	
	class ExileTrack05 {
		duration = 317;
		musicClass = "Calm";
		name = "Exile Track 05 - The Island Minor (Roaming Ambience)";
		sound[] = {"", 1, 1};
	};
	
	class ExileTrack06 {
		duration = 115;
		musicClass = "Action";
		name = "Exile Track 06 - Lethal Force (Combat Soundtrack)";
		sound[] = {"", 1, 1};
	};
	
	class ExileTrack07 {
		duration = 157;
		musicClass = "Action";
		name = "Exile Track 07 - LethalForce v2 (Combat Soundtrack)";
		sound[] = {"", 1, 1};
	};

	class LoadingScreenMusic {
		duration = 15;
		musicClass = "Action";
		name = "Aggressor";
		sound[] = {"\kfb_assets\sound\aggressor.ogg", 1, 1};
	};
};
