// Generated by unRap v1.06 by Kegetys

class CfgMods {
	class Mod_Base;	// External class reference
	
	class Exile : Mod_Base {
		name = "";
		author = "Exile Mod Team";
		action = "";
		dir = "@Exile";
		logo = "exile_assets\texture\mod\logo.paa";
		logoOver = "exile_assets\texture\mod\logo.paa";
		logoSmall = "";
		picture = "exile_assets\texture\mod\logo.paa";
		hidePicture = 0;
		hideName = 0;
		dlcColor[] = {0.94, 0.29, 0.98, 1};
		version = 1.0.41;
		armaVersion = 180;
		overview = "";
		itemPrevNotifText = "";
	};
};
