// Generated by unRap v1.06 by Kegetys

class CfgXM8 {
	class apps {
		controlID = 4040;
		title = XM8;
	};
	
	class players {
		controlID = 4110;
		title = "8G Network";
	};
	
	class clan {
		controlID = 4060;
		title = "Family";
	};
	
	class hostParty {
		controlID = 4080;
		title = "Host Party";
	};
	
	class party {
		controlID = 4100;
		title = "Party";
	};
	
	class server {
		controlID = 4090;
		title = "Server Info";
	};
	
	class territory {
		controlID = 4130;
		title = "Territory";
	};
	
	class mobileXm8 {
		controlID = 4200;
		title = "Discord";
	};
	
	class extraApps {
		controlID = 5000;
		title = XM8;
	};
};
