// Generated by unRap v1.06 by Kegetys

class RscDisplayMultiplayerSetup : RscStandardDisplay {
	access = ReadOnlyVerified;
	onLoad = "with uiNameSpace do { [_this select 0, 'RscDisplayLoadMission'] call ExileClient_gui_loadingScreen_load; };";
	onUnload = "with uiNameSpace do { (_this select 0) call ExileClient_gui_loadingScreen_unload; };";
	class scriptName {};
	class scriptPath {};
	
	class controlsbackground {
		class TileGroup : RscControlsGroupNoScrollbars {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class Vignette : RscVignette {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class RscTitleBackground : RscText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class MainBackground : RscText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class MissionSettingsBackground : RscText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class NumOfPlayersBackground : RscText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class SideBackground : RscText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class PlayersPoolHeaderBackground : RscText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class RolesBackground : RscText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class ChatBackground : RscText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class PlayersPoolBackground : RscText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class ExileBlackBackground : RscText {
			idc = -1;
			colorBackground[] = {0, 0, 0, 1};
			x = "safezoneXAbs";
			y = "safezoneY";
			w = "safezoneWAbs";
			h = "safezoneH";
		};
		
		class ExileBackgroundPicture : RscPicture {
			idc = 66000;
			x = "safezoneX";
			y = "safezoneY";
			w = "safezoneW";
			h = "safezoneW * 4/3";
			text = "exile_assets\texture\loading\loading_cheathas_co.paa";
		};
	};
	
	class controls {
		class SortPing : RscPicture {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class SortPlayers : RscPicture {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class Y_GamerCard : RscActiveText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class PartyGUI : RscActiveText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class MuteAll : RscCheckBox {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class AssignRole : RscActiveText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class ButtonPlayers : RscButtonTextOnly {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class ButtonPing : ButtonPlayers {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class Title : RscTitle {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class PlayersName : RscTitle {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class CA_TextVotingTimeLeft : RscTitle {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class ValueMission : RscTitle {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class CA_TextDescription : RscText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class CA_ValueDescription : RscText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class TextIsland : RscText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class ValueIsland : RscText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class TextSide : RscText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class CA_B_West : RscActiveText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class CA_B_Logic : CA_B_West {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class CA_B_East : CA_B_West {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class CA_B_Guerrila : CA_B_West {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class CA_B_Civilian : CA_B_West {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class CA_B_Virtual : CA_B_West {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class CA_ValueRoles : RscListBox {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class CA_ValuePool : RscListNBox {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class CA_B_EnableAll : RscButtonMenu {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class CA_B_Lock : RscButtonMenu {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class CA_B_Params : RscButtonMenu {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class ButtonSteamWorkshop : RscButtonMenuSteam {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class CA_B_Kick : RscButtonMenu {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class CA_ButtonContinue : RscButtonMenuOK {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class CA_ButtonCancel : RscButtonMenuCancel {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class TextMission : RscText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class TextRole : RscText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class TextPlayersPool : RscText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class TextListedPlayers : RscText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class ValueListedPlayers : RscText {
			x = -1;
			y = -1;
			h = 0;
			w = 0;
			show = 0;
		};
		
		class ExileSpinnerPicture : RscPicture {
			idc = 66001;
			x = "safeZoneX + 60 * pixelW";
			y = "safeZoneY + safeZoneH - (60 + 64) * pixelH";
			w = "64 * pixelW";
			h = "64 * pixelH";
			text = "exile_assets\texture\loading\spinner_ca.paa";
			type = VSoft;
			centerU = 0.5;
			centerV = 0.5;
			angle = 90;
			show = 0;
		};
		
		class ExileSpinnerTitle : RscStructuredText {
			idc = 66002;
			text = "<t>Still loading...</t>";
			x = "safeZoneX + 60 * pixelW";
			y = "safeZoneY + safeZoneH - (60 + 64 - 10) * pixelH";
			w = "safeZoneW - (60 + 64 + 15) * pixelW";
			h = "64 * pixelH";
			size = "44 * pixelH";
			sizeEx = "44 * pixelH";
			colorText[] = {1, 1, 1, 1};
			shadow = false;
			
			class Attributes {
				font = "RobotoMedium";
				color = "#ffffff";
				colorLink = "#ffffff";
				align = "left";
				shadow = false;
			};
		};
		
		class ExileLogo : RscControlsGroupNoScrollbars {
			idc = -1;
			
			
			class controls {
			};
		};
		
		class ExileMap : RscControlsGroupNoScrollbars {
			idc = 66003;
			x = "safeZoneX + safeZoneW - (60 + 380) * pixelW";
			y = "safeZoneY + (60 + 60 + 30) * pixelH";
			w = "380 * pixelW";
			h = "(190 + 30 + 20) * pixelH";
			show = 0;
			
			class controls {
				class ExileMapBackground : RscText {
					idc = -1;
					colorBackground[] = {0, 0, 0, 0};
					x = 0;
					y = 0;
					w = "380 * pixelW";
					h = "(190 + 30 + 20) * pixelH";
				};
				
				class ExileMapPictureBackground : RscText {
					idc = -1;
					colorBackground[] = {18/255, 19/255, 21/255, 0};
					x = 0;
					y = 0;
					w = "380 * pixelW";
					h = "190 * pixelH";
				};
				
				class ExileMapPicture : RscPicture {
					idc = 66004;
					text = "";
					x = 0;
					y = 0;
					w = "380 * pixelW";
					h = "190 * pixelH";
				};
				
				class ExileMapName : RscText {
					idc = 66005;
					text = "";
					font = "RobotoMedium";
					x = 0;
					y = "(190 + 1) * pixelH";
					w = "380 * pixelW";
					h = "30 * pixelH";
					sizeEx = "24 * pixelH";
					colorText[] = {1, 1, 1, 1};
					shadow = false;
					style = 192;
				};
				
				class ExileMapAuthor : RscText {
					idc = 66006;
					text = "";
					font = "RobotoCondensedLight";
					x = 0;
					y = "(190 + 25 - 1) * pixelH";
					w = "380 * pixelW";
					h = "20 * pixelH";
					sizeEx = "20 * pixelH";
					colorText[] = {151/255, 155/255, 161/255, 1};
					shadow = false;
				};
			};
		};
		
		class ExileMission : RscControlsGroupNoScrollbars {
			idc = 66007;
			x = "safeZoneX + safeZoneW - (60 + 380) * pixelW";
			y = "safeZoneY + (60 + 60 + 30 + 190 + 30 + 20 + 30) * pixelH";
			w = "380 * pixelW";
			h = "(190 + 30 + 20) * pixelH";
			show = 0;
			
			class controls {
				class ExileMissionBackground : RscText {
					idc = -1;
					colorBackground[] = {0, 0, 0, 0};
					x = 0;
					y = 0;
					w = "380 * pixelW";
					h = "(190 + 30 + 20) * pixelH";
				};
				
				class ExileMissionPictureBackground : RscText {
					idc = -1;
					colorBackground[] = {18/255, 19/255, 21/255, 0};
					x = 0;
					y = 0;
					w = "380 * pixelW";
					h = "190 * pixelH";
				};
				
				class ExileMissionPicture : RscPictureKeepAspect {
					idc = 66008;
					text = "";
					x = 0;
					y = 0;
					w = "380 * pixelW";
					h = "190 * pixelH";
				};
				
				class ExileMissionName : RscText {
					idc = 66009;
					text = "";
					font = "RobotoMedium";
					x = 0;
					y = "(190 + 1) * pixelH";
					w = "380 * pixelW";
					h = "30 * pixelH";
					sizeEx = "24 * pixelH";
					colorText[] = {1, 1, 1, 1};
					shadow = false;
					style = 192;
				};
				
				class ExileMissionAuthor : RscText {
					idc = 66010;
					text = "";
					font = "RobotoCondensedLight";
					x = 0;
					y = "(190 + 25 - 1) * pixelH";
					w = "380 * pixelW";
					h = "20 * pixelH";
					sizeEx = "20 * pixelH";
					colorText[] = {151/255, 155/255, 161/255, 1};
					shadow = false;
				};
			};
		};
	};
};
