// Generated by unRap v1.06 by Kegetys

class RscExilePrimaryButton : RscButton {
	w = "300 * pixelW";
	h = "60 * pixelH";
	colorBackground[] = {199/255, 38/255, 81/255, 1};
	colorText[] = {1, 1, 1, 1};
	shadow = false;
	font = "RobotoMedium";
	sizeEx = "30 * pixelH";
	colorFocused[] = {199/255, 38/255, 81/255, 0.8};
	colorBackgroundActive[] = {199/255, 38/255, 81/255, 0.8};
};
