// Generated by unRap v1.06 by Kegetys

class RscExileSelectSpawnLocationDialog {
	idd = 24002;
	access = ReadOnlyVerified;
	duration = -1;
	onLoad = "uiNamespace setVariable ['RscExileSelectSpawnLocationDialog', _this select 0]; with uiNameSpace do { [_this select 0, 'RscExileSelectSpawnLocationDialog'] call ExileClient_gui_loadingScreen_load; };";
	onUnload = "with uiNameSpace do { (_this select 0) call ExileClient_gui_loadingScreen_unload; }; uiNamespace setVariable ['RscExileSelectSpawnLocationDialog', displayNull]";
	
	class controlsBackground {
		class ExileBlackBackground : RscText {
			idc = -1;
			colorBackground[] = {0, 0, 0, 1};
			x = "safezoneXAbs";
			y = "safezoneY";
			w = "safezoneWAbs";
			h = "safezoneH";
		};
		
		class ExileBackgroundPicture : RscPicture {
			idc = 66000;
			x = "safezoneX";
			y = "safezoneY";
			w = "safezoneW";
			h = "safezoneW * 4/3";
			text = "exile_assets\texture\loading\loading_cheathas_co.paa";
		};
	};
	
	class controls {
		class ExileLogo : RscControlsGroupNoScrollbars {
			idc = -1;
			
			
			class controls {
			};
		};
		
		class ExileMap : RscControlsGroupNoScrollbars {
			idc = 66003;
			x = "safeZoneX + safeZoneW - (60 + 380) * pixelW";
			y = "safeZoneY + (60 + 60 + 30) * pixelH";
			w = "380 * pixelW";
			h = "(190 + 30 + 20) * pixelH";
			show = 0;
			
			class controls {
				class ExileMapBackground : RscText {
					idc = -1;
					colorBackground[] = {0, 0, 0, 0};
					x = 0;
					y = 0;
					w = "380 * pixelW";
					h = "(190 + 30 + 20) * pixelH";
				};
				
				class ExileMapPictureBackground : RscText {
					idc = -1;
					colorBackground[] = {18/255, 19/255, 21/255, 0};
					x = 0;
					y = 0;
					w = "380 * pixelW";
					h = "190 * pixelH";
				};
				
				class ExileMapPicture : RscPicture {
					idc = 66004;
					text = "";
					x = 0;
					y = 0;
					w = "380 * pixelW";
					h = "190 * pixelH";
				};
				
				class ExileMapName : RscText {
					idc = 66005;
					text = "";
					font = "RobotoMedium";
					x = 0;
					y = "(190 + 1) * pixelH";
					w = "380 * pixelW";
					h = "30 * pixelH";
					sizeEx = "24 * pixelH";
					colorText[] = {1, 1, 1, 1};
					shadow = false;
					style = 192;
				};
				
				class ExileMapAuthor : RscText {
					idc = 66006;
					text = "";
					font = "RobotoCondensedLight";
					x = 0;
					y = "(190 + 25 - 1) * pixelH";
					w = "380 * pixelW";
					h = "20 * pixelH";
					sizeEx = "20 * pixelH";
					colorText[] = {151/255, 155/255, 161/255, 1};
					shadow = false;
				};
			};
		};
		
		class ExileMission : RscControlsGroupNoScrollbars {
			idc = 66007;
			x = "safeZoneX + safeZoneW - (60 + 380) * pixelW";
			y = "safeZoneY + (60 + 60 + 30 + 190 + 30 + 20 + 30) * pixelH";
			w = "380 * pixelW";
			h = "(190 + 30 + 20) * pixelH";
			show = 0;
			
			class controls {
				class ExileMissionBackground : RscText {
					idc = -1;
					colorBackground[] = {0, 0, 0, 0};
					x = 0;
					y = 0;
					w = "380 * pixelW";
					h = "(190 + 30 + 20) * pixelH";
				};
				
				class ExileMissionPictureBackground : RscText {
					idc = -1;
					colorBackground[] = {18/255, 19/255, 21/255, 0};
					x = 0;
					y = 0;
					w = "380 * pixelW";
					h = "190 * pixelH";
				};
				
				class ExileMissionPicture : RscPictureKeepAspect {
					idc = 66008;
					text = "";
					x = 0;
					y = 0;
					w = "380 * pixelW";
					h = "190 * pixelH";
				};
				
				class ExileMissionName : RscText {
					idc = 66009;
					text = "";
					font = "RobotoMedium";
					x = 0;
					y = "(190 + 1) * pixelH";
					w = "380 * pixelW";
					h = "30 * pixelH";
					sizeEx = "24 * pixelH";
					colorText[] = {1, 1, 1, 1};
					shadow = false;
					style = 192;
				};
				
				class ExileMissionAuthor : RscText {
					idc = 66010;
					text = "";
					font = "RobotoCondensedLight";
					x = 0;
					y = "(190 + 25 - 1) * pixelH";
					w = "380 * pixelW";
					h = "20 * pixelH";
					sizeEx = "20 * pixelH";
					colorText[] = {151/255, 155/255, 161/255, 1};
					shadow = false;
				};
			};
		};
		
		class DialogBackground : RscText {
			idc = -1;
			x = "safeZoneX + 60 * pixelW";
			y = "safeZoneY + 60 * pixelH";
			w = "safeZoneW - (60 + 60 + 380 + 60) * pixelW";
			h = "safeZoneH - (60 + 60) * pixelH";
			colorBackground[] = {32/255, 36/255, 42/255, 1};
		};
		
		class DialogTitleBackground : RscText {
			idc = -1;
			x = "safeZoneX + 60 * pixelW";
			y = "safeZoneY + 60 * pixelH";
			w = "safeZoneW - (60 + 60 + 380 + 60) * pixelW";
			h = "60 * pixelH";
			colorBackground[] = {0, 0, 0, 1};
		};
		
		class DialogTitle : RscText {
			idc = -1;
			x = "safeZoneX + (60 + 15) * pixelW";
			y = "safeZoneY + 60 * pixelH";
			w = "safeZoneW - (60 + 60 + 380 + 60 + 60 + 10) * pixelW";
			h = "60 * pixelH";
			text = "Spawn Location";
			sizeEx = "30 * pixelH";
			font = "RobotoCondensed";
		};
		
		class ListBoxLocations : RscListBox {
			idc = 24002;
			text = "Locations";
			font = "RobotoCondensed";
			x = "safeZoneX + (60 + 15) * pixelW";
			y = "safeZoneY + (60 + 60 + 15) * pixelH";
			w = "300 * pixelW";
			h = "safeZoneH - (60 + 60 + 60 + 15 + 15 + 60 + 15) * pixelH";
			colorBackground[] = {0, 0, 0, 0.25};
			onLBSelChanged = "_this call ExileClient_gui_selectSpawnLocation_event_onListBoxSelectionChanged;";
		};
		
		class Map : RscMapControl {
			idc = 24001;
			text = "";
			x = "safeZoneX + (60 + 15 + 300 + 15) * pixelW";
			y = "safeZoneY + (60 + 60 + 15) * pixelH";
			w = "safeZoneW - (60 + 15 + 300 + 15 + 15 + 60 + 380 + 60) * pixelW";
			h = "safeZoneH - (60 + 60 + 15 + 60 + 15) * pixelH";
			moveOnEdges = 0;
			maxSatelliteAlpha = 0.75;
			alphaFadeStartScale = 1.15;
			alphaFadeEndScale = 1.29;
		};
		
		class ButtonSpawn : RscExilePrimaryButton {
			idc = 24003;
			text = OKAY;
			x = "safeZoneX + (60 + 15) * pixelW";
			y = "safeZoneY + safeZoneH - (60 + 15 + 60) * pixelH";
			w = "300 * pixelW";
			h = "60 * pixelH";
			onButtonClick = "[] call ExileClient_gui_selectSpawnLocation_event_onSpawnButtonClick";
		};
	};
};
