// Generated by unRap v1.06 by Kegetys

class RscExileXM8Button : RscExileXM8AppButton1x1 {
	height = 2 * (0.04);
	size = "(			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)";
	
	class Attributes {
		align = "center";
	};
	
	class AttributesImage {
		align = "center";
		color = "#E5E5E5";
		font = "PuristaMedium";
	};
	
	class TextPos {
		bottom = 0;
		left = 0;
		right = 0;
		top = (1 * (0.04)) * 0.5;
	};
};
