// Generated by unRap v1.06 by Kegetys

class RscExileXM8AppButton1x1 : RscExileXM8AppButton {
	w = 6 * (0.025);
	h = 5 * (0.04);
	textureNoShortcut = "";
	text = "";
	
	class ShortcutPos {
		left = (6 * (0.025)) * 0.25;
		top = (5 * (0.04)) * 0.15;
		w = (6 * (0.025)) * 0.5;
		h = (5 * (0.04)) * 0.5;
	};
	
	class TextPos {
		bottom = 0;
		left = 0;
		right = 0;
		top = (5 * (0.04)) * 0.65;
	};
};
