// Generated by unRap v1.06 by Kegetys

class RscExileXM8AppButton2x1 : RscExileXM8AppButton1x1 {
	w = 12.5 * (0.025);
	
	class ShortcutPos {
		left = (12.5 * (0.025)) * 0.5 - (6 * (0.025)) * 0.25;
		top = (5 * (0.04)) * 0.15;
		w = (6 * (0.025)) * 0.5;
		h = (5 * (0.04)) * 0.5;
	};
};
