// Generated by unRap v1.06 by Kegetys

class RscExileXM8Slide {
	deletable = 0;
	fade = 0;
	shadow = false;
	style = 16;
	type = 15;
	x = 0 * (0.025);
	y = 0 * (0.04);
	w = 34 * (0.025);
	h = 19 * (0.04);
	show = "false";
	
	class Controls {};
	
	class HScrollbar : Scrollbar {
		show = "false";
	};
	
	class VScrollbar : Scrollbar {
		show = "false";
	};
};
